### ISSUE TITLE
The type of coins is indicated incorrectly, when trying to throw them away or trade with another character

### ISSUE THREAD

**Issue by Reotor** [grannypron/PoR_L10n#103]
When trying to throw coins to the ground, when we go: VIEW ---> DROP (or just trade with another character from my party), despite the fact that the character has only gold (ЗОЛОТО) coins and they are selected, the question is asked - how much **platinum** (ПЛАТИНА) to throw away.

![gold_n_platina](https://user-images.githubusercontent.com/77742895/126048192-db5d66df-bd15-4452-b916-8f9926e9ec87.jpg)

When you try to specify the number of coins to be thrown away, the number is automatically set to zero (doesn't matter what value I wrote).

![gold_n_platina2](https://user-images.githubusercontent.com/77742895/126048212-845285ce-2052-4329-9c6f-e62693804007.jpg)

In the original, everything is written correctly, gold is indicated:

![gold](https://user-images.githubusercontent.com/77742895/126048236-c6d189a4-16d0-423b-b228-c5e587cf409b.jpg)

**Comment by grannypron** [comment]
Interesting that I can't even get to this command anymore because of #142, so a commit between Jul 17 and now caused #142.

**Comment by grannypron** [comment]
What I would try here next is seeing if the lengthening of the "GOLD" and other strings are the cause of the problem

**Comment by grannypron** [comment]
Changing the translation of GOLD from Золото to Зол. does not seem to fix the problem

**Comment by grannypron** [comment]
Next strategy is to start commenting out large portions of start.exe.translations.txt to see which changes cause the error and that will hopefully give some ideas for a cause/solution.

**Comment by grannypron** [comment]
OK i believe this has something to do with the Jewel vs Jewelry translation.  If I comment out 105-100, 218, 227, and 327, things start working correctly.

**Comment by grannypron** [comment]
I think I need to change the order of 227 and and 327 and maybe 218 and 110?  so that the plural gets swapped first before the singluar.

**Comment by grannypron** [comment]
Apart from words not being translated, leaving these translations out of START.EXE seem to prevent all the problems in this ticket:
108, 109, 110, 218, 227, 292, 293, 327

I think somehow maybe the lengths of the currencies seem to be mattering.

**Comment by grannypron** [comment]
Still, changing 108 & 292 both to Зол. has the same problem.  Perhaps the . character?

**Comment by grannypron** [comment]
Nope using Золв for 108 and 292 does not work.  Perhaps Gold is in there more times than I think and I am missing it.

**Comment by grannypron** [comment]
For Gold, it seems to be related to the related to the first letter.  Пол. works, but Дол. and Зол. do not.

**Comment by grannypron** [comment]
It's not just Gold.  The same is true for Platinum.  I can call it anything as long as it starts with P.   There must be some kind of indexing of the coinage by the first letter somewhere in the game...

**Comment by grannypron** [comment]
Got it.  GAME.OVR at 2585D has quite a few 3C tests that seem to correspond with the first letter of each currency type.  If I turn 2585E to "P", after changing Gold to Зол. (because P = З), it seems to work.  However there is another 3C test for "P" a little later on at 258AC which corresponds to Platinum, so I have to change that to "G" (because Platinum = Платина and П = G) - which , funny enough, just means the P & G at those two locations get swapped.  Anyway, changing those values around that block of code should set things straight.

**Comment by grannypron** [comment]
OK they all work now except for Gems.   The reason that Gems doesn't work now is because the game uses the following logic:
1) Check to see if the first character is a "G" and if so, 
1a) Check to see if the second character is "E" and if so, use Gems
1b) Otherwise, use Gold
2) Check to see if the first character is "P" and if so use Platinum
3) Check to see if the first character is "E" and if so use Electrum
...

So, the game expects that the first characters for Gold and Gems are the same letter :/

**Comment by grannypron** [comment]
OK for now I put it as Зам. to prove my diagnosis and make it work.  Let me know if there is a word for Gold and Gems that both start with the same letter.    And that letter does not conflict with the first letter of any of the other currency types.

If not, maybe we can try starting them with a space (20) or some other character and change the comparison to 20 instead of "G"?  Changing the structure of the IF jmps would likely be pretty tricky.

**Comment by Reotor** [comment]
> Let me know if there is a word for Gold and Gems that both start with the same letter.

I have sent a request to our forum. Nothing comes to my mind yet ...
https://www.old-games.ru/forum/threads/pool-of-radiance.97690/page-33#post-1761878

**Comment by Reotor** [comment]
It is unlikely that we will be able to make both words with the same letter. But if we can shift the hotkey to the second letter, then the word "И**З**УМРУДЫ" may be a suitable translation option for "GEMS". (Second letter is "З" ---> **З**ОЛОТО).

**Comment by Reotor** [comment]
If this option does not help, then it is better to leave the previous translation and try to solve this problem in another way (if possible).

**Comment by grannypron** [comment]
Using a space before Зол. and changing the hotkey test to 20 does NOT seem to work.  Seems to look for the first non-space character.  I suppose we could prefix both Зол. and Кам with "." ?

**Comment by Reotor** [comment]
> I suppose we could prefix both Зол. and Кам with "." ?

- Firstly, if we use a dot at the end of the "Зол." word (indicating that this is an abbreviation), then we need to put a dot at the end of the "Кам" word too (since this is also an abbreviation) for simmetry.
- Secondly, if I understand correctly, are you going to add a dot at the beginning of each of these words so that they start with the same character? Did I understand correctly? If so and if it will be visible, then maybe we will come up with some other version of the symbol, which will be more appropriate to look at the beginning of these words and will emphasize their meaning? For example, it could be $ or something like that ... What variants of symbols do we have other than dots?

**Comment by grannypron** [comment]
Yep, right now I have a . at the end of Кам as well

You do understand correctly.  Theoretically, yes we could use a separate character, but I don't think there are many options left for us to choose that the game doesn't need :/   It's an option that we will keep on the table.  I will look at changing the if statement logic next, even if it will be tricky.

**Comment by grannypron** [comment]
Not sure if the G/E letter checking is done when the coin type is chosen or when the amount is entered.  

Discovery: 24F8F in GAME.OVR is where the input bounds are checked (3C30 and 3C39 is checking for to see if the ASCII value is between 0 and 9)

**Comment by grannypron** [comment]
Verified, I reach the cmp al,47 instruction at 2B9B:0BD4 when the Enter key is pressed to choose the coin type, not when I enter the amount.

**Comment by grannypron** [comment]
Here, then, are the relevant instructions from the DOSBOX debugger:

2B9B:0BD4  3C47                cmp  al,47                                       
2B9B:0BD6  754A                jne  00000C22 ($+4a)        (down)               
2B9B:0BD8  8A86FEFE            mov  al,[bp-0102]           ss:[3A2E]=0A05       
2B9B:0BDC  30E4                xor  ah,ah                                       
2B9B:0BDE  40                  inc  ax                                          
2B9B:0BDF  8BF8                mov  di,ax                                       
2B9B:0BE1  8A83FFFE            mov  al,[bp+di-0101]        ss:[3A34]=6547       
2B9B:0BE5  50                  push ax                                          
2B9B:0BE6  9A2A189A0C          call 0C9A:182A                                   
2B9B:0BEB  3C45                cmp  al,45                                       
2B9B:0BED  7519                jne  00000C08 ($+19)        (down)               
2B9B:0BEF  C646FF05            mov  byte [bp-01],05        ss:[3B2F]=7200       
2B9B:0BF3  BF5A0B              mov  di,0B5A                                     
2B9B:0BF6  0E                  push cs                                          
2B9B:0BF7  57                  push di                                          
2B9B:0BF8  C47E06              les  di,[bp+06]             ss:[3B36]=3C45       
2B9B:0BFB  06                  push es                                          
2B9B:0BFC  57                  push di                                          
2B9B:0BFD  B8FF00              mov  ax,00FF                                     
2B9B:0C00  50                  push ax                                          
2B9B:0C01  9A250B9A0C          call 0C9A:0B25                                   
2B9B:0C06  EB17                jmp  short 00000C1F ($+17)  (down)               
2B9B:0C08  BF600B              mov  di,0B60                                     
2B9B:0C0B  0E                  push cs                                          
2B9B:0C0C  57                  push di                                          
2B9B:0C0D  C47E06              les  di,[bp+06]             ss:[3B36]=3C45       
2B9B:0C10  06                  push es                                          
2B9B:0C11  57                  push di                                          
2B9B:0C12  B8FF00              mov  ax,00FF                                     
2B9B:0C15  50                  push ax                                          
2B9B:0C16  9A250B9A0C          call 0C9A:0B25                                   
2B9B:0C1B  C646FF03            mov  byte [bp-01],03        ss:[3B2F]=7200       
2B9B:0C1F  E98F00              jmp  00000CB1 ($+8f)        (down)               
2B9B:0C22  3C50                cmp  al,50                                       
2B9B:0C24  7519                jne  00000C3F ($+19)        (down)               
2B9B:0C26  BF660B              mov  di,0B66                                     
2B9B:0C29  0E                  push cs                                          
2B9B:0C2A  57                  push di                                          
2B9B:0C2B  C47E06              les  di,[bp+06]             ss:[3B36]=3C45

**Comment by grannypron** [comment]
The G/E/first coin selection decision has been made by this instruction, because this is where the amount input is collected:

28E9:23F5  9A3E003102          call 0231:003E

**Comment by grannypron** [comment]
OK at 2B9B:0C24 we can see that we jump $+19 if the first character is not P (50), which jumps to 0C3F, which is the very next cmp,45 (for Electrum)

So, let's change 2B9B:0BD6 to not jump +4a because that will jump past the cmp,45 check for E that is for gems.  Instead  2B9B:0BD6 should jump to 0BEB.   

But, be careful because, the difference between 0C24 and 0C3F is 1B - we need to account for the two bytes of the jump instruction itself (7519)

**Comment by grannypron** [comment]
So, the jump at 0BD6 needs to be +13 because 0BD6+13+2 = 0BEB, so we change 754A to 7513 at 0BD6 and 0BD6 maps to 2585F-25860 in GAME.OVR, so this change should be

**25860|13

**Comment by grannypron** [comment]
Holy crap that works

**Comment by grannypron** [comment]
Dangit now the other coin types stopped working

**Comment by Reotor** [comment]
> Dangit now the other coin types stopped working

May I clarify? Are you trying to make it so that we can do without having to write the same character at the beginning of these words?

**Comment by grannypron** [comment]
Yes, this is to remove the limitation that both Gold and Gems translation have to start with the same letter by changing the assembly code.

Looks like 2B9B:0BED's jmp statement needs to jump a little farther now.  This is probably because that if statement was inside the first if statement originally.  Looks like 2B9B:0BED should jump to 2B9B:0C22 instead of 0C08 - which means it needs to be +33 instead of +19 - this maps to 25877 in GAME.OVR

**Comment by grannypron** [comment]
No, that makes Gold not work.  This is because we jump over the "Not E" clause somehow...

OK so 0C08 was the old "Gold" clause.
0C22 is the "Neither Gold nor Gems" clause.

**Comment by grannypron** [comment]
But now G is not working.  That is because when the value is G, it is doing some junk that is screwing up future comparisons or operations between 2B9B:0BD8 and 2B9B:0BEB.  The real logic for G should start at the jne destination when the cmp,45 fails - that being 0C08.  So, I changed the first op at 2B9B:0BD8 to just jump straight to 0C08 and it seems to work just fine.

**Comment by grannypron** [comment]
Jewelry and Platinum are not working in the latest version

**Comment by grannypron** [comment]
Or Copper, Silver, Electrum.  :(

**Comment by grannypron** [comment]
Jump at 0BED needed an adjustment because it was ending up right in the middle of something where it should not have been. Not exactly sure why.
