### ISSUE TITLE
"REST" option not work while encamp

### ISSUE THREAD

**Issue by Reotor** [grannypron/PoR_L10n#105]
"СОН" (REST) option not work while encamp.

![rest](https://user-images.githubusercontent.com/77742895/126050316-3211814a-4d3e-4b3c-bfe0-b60490281b2a.jpg)

I press the "С" hotkey and nothing happens. It may be necessary to check if the hotkey is set correctly here.

However, when I select an "УЙТИ" (EXIT) option, instead of just exiting to the previous menu, rest occurs.

**Comment by grannypron** [comment]
I believe the hotkey is set correctly at 2459A in GAME.OVR and is set to C.

**Comment by grannypron** [comment]
CPU instruction traces from the original and modded games are attached.  You can see a divergence early on here:

(unmodded)
2B64:00000771  cmp  byte [bp-02],00            ss:[3E76]=0001         EAX:00000013 EBX:00003C8A ECX:00000000 EDX:00000E1E ESI:00003C97 EDI:00003E76 EBP:00003E78 ESP:00003E4A DS:0E1E ES:1694 FS:0000 GS:0000 SS:1694 CF:0 ZF:1 SF:0 OF:0 AF:0 PF:1 IF:

vs (modded)
2B64:00000771  cmp  byte [bp-02],00            ss:[3E76]=0000         EAX:00000043 EBX:00000008 ECX:00000003 EDX:00000027 ESI:00003C97 EDI:00003E76 EBP:00003E78 ESP:00003E4A DS:0E1E ES:1694 FS:0000 GS:0000 SS:1694 CF:0 ZF:1 SF:0 OF:0 AF:0 PF:1 IF:1


Note the 0001 vs 0000 at ss:[3E76]

[LOGCPU_GH105_R_OrigGame.TXT](https://github.com/grannypron/PoR_L10n/files/7181778/LOGCPU_GH105_R_OrigGame.TXT)

[LOGCPU_GH105_C_ModdedGame.TXT](https://github.com/grannypron/PoR_L10n/files/7181776/LOGCPU_GH105_C_ModdedGame.TXT)
1

**Comment by grannypron** [comment]
Also, in the original, Exiting does NOT cause the rest to take place before the screen exits.

**Comment by grannypron** [comment]
Nah that earlier log was junk.  Better log attached.   

[LOGCPU_GH105_R_OrigGame2.TXT](https://github.com/grannypron/PoR_L10n/files/7230511/LOGCPU_GH105_R_OrigGame2.TXT)

Real divergence is here:

Modded:
0C9A:00000DDB  test es:[bx+di],al              es:[0709]=0020         EAX:00000008 EBX:00000008 ECX:00000003 EDX:00000027 ESI:00003C97 EDI:00000701 EBP:00003E78 ESP:00003E40 DS:0E1E ES:2B64 FS:0000 GS:0000 SS:1694 CF:0 ZF:0 SF:0 OF:0 AF:1 PF:0 IF:1

vs original:
0C9A:00000DDB  test es:[bx+di],al              es:[070B]=0004         EAX:00000004 EBX:0000000A ECX:00000002 EDX:00000027 ESI:00003C97 EDI:00000701 EBP:00003E78 ESP:00003E40 DS:0E1E ES:2B64 FS:0000 GS:0000 SS:1694 CF:0 ZF:0 SF:0 OF:0 AF:1 PF:0 IF:1

That 20 & 04 map to 244D5-244D7 in GAME.OVR.  Need to change that 20 to 28 so that when AL (8) is AND'ed with it, zero flag remains 0.
