### ISSUE TITLE
Please change the font to the one I provide you

### ISSUE THREAD

**Issue by Reotor** [grannypron/PoR_L10n#124]
Grongy tweaked the font to fix some additional overlapping issues. Here is this font:

![fixed](https://user-images.githubusercontent.com/77742895/126910204-a6279721-c7a7-46a8-9588-2a7402c25e8f.png)

Use this font for the next patch please.

**Comment by grannypron** [comment]
If I do that, it is going to overwrite the fix for the #80 with the Ё character, which required a font change.  We are working over top of each other.  This is the one I used:
[01. Pool of Radiance-RU - Copy.bmp.zip](https://github.com/grannypron/PoR_L10n/files/6874561/01.Pool.of.Radiance-RU.-.Copy.bmp.zip)

**Comment by Reotor** [comment]
The fact is that you still have to use a different font, since the font you are showing is missing a letter "Х" and has a wrong dot

**Comment by Reotor** [comment]
Or will it be easier for you if I take this font and ask Grongy to make changes right in it?

**Comment by grannypron** [comment]
The one I just used to fix #120 is attached.  I can set it to whatever you like, but be aware that I made the change for the fix for #80 (pixels 248x0 to 255x7).   The one I used is attached.  I need it to be in a bmp format with simple black and white, no anti-aliasing (with shades of grey)
[01. Pool of Radiance-RU.zip](https://github.com/grannypron/PoR_L10n/files/6874605/01.Pool.of.Radiance-RU.zip)

**Comment by Reotor** [comment]
Perhaps this version will fits? 

[fixed_font__Reotor.zip](https://github.com/grannypron/PoR_L10n/files/6874615/fixed_font__Reotor.zip)

I just made it myself by adding the letter "Ё" in the same place where it be in your font to Grongy's new font and save it as bmp with the same parameters as you said.

**Comment by Reotor** [comment]
Grongy redesigned the font with the pixel offsets you specified:

[fixed2_Grongy.zip](https://github.com/grannypron/PoR_L10n/files/6875797/fixed2_Grongy.zip)

_*There was a slight inaccuracy in my version..._

**Comment by grannypron** [comment]
I couldn't tell any difference except that one had the first row shifted to the right by a pixel, but I put it in the patch.

**Comment by Reotor** [comment]
Thank you, but why is the letter "Ё" and quotes still missing in the [latest patch](https://github.com/grannypron/PoR_L10n/issues/124)?

**That is, these issues are relevant again:**

https://github.com/grannypron/PoR_L10n/issues/80
https://github.com/grannypron/PoR_L10n/issues/78

![JO](https://user-images.githubusercontent.com/77742895/127102017-0a7dde19-0169-4ef8-8b3a-5e146a92cd8e.jpg)

In one of the previous patches, this was already fixed. And in the latest version of the font, this letter is already in the same place where it was in your first font.

![fonts](https://user-images.githubusercontent.com/77742895/127103648-94a9669a-0a96-4d44-bac6-b5359545fcbf.jpg)

**Comment by Reotor** [comment]
**[Can you please make a patch for us, where these main issues will be solved?](https://github.com/grannypron/PoR_L10n/issues/125)**
