### ISSUE TITLE
Your ---> It is necessary to replace it with a space or in some other way to remove this string from the game, because it conflicts with the current settings for multiple stacking items

### ISSUE THREAD

**Issue by grannypron** [grannypron/PoR_L10n#14]
[389](https://www.old-games.ru/translate/index.php?translationid=152&page=all#phrase389) Your ---> It is necessary to replace it with a space or in some other way to remove this string from the game, because it conflicts with the current settings for multiple stacking items

![vash](https://user-images.githubusercontent.com/77742895/115527098-6a2d9400-a299-11eb-8f58-cd4c81896014.jpg)

_Originally posted by @Reotor in https://github.com/grannypron/PoR_L10n/issues/12#issuecomment-823903106_

**Comment by grannypron** [comment]
Should be in the latest patch.

**Comment by Reotor** [comment]
Unfortunately, the problem has not been resolved. Instead of the word "Ваш", Latin characters appeared. I believe it is necessary to replace the word "Ваш" with a space (just leave a blank space on the string, like this "  ").

![your](https://user-images.githubusercontent.com/77742895/116570220-c5ebc300-a912-11eb-8557-ff783bb9ef55.jpg)
