### ISSUE TITLE
Drop ---> Уд.

### ISSUE THREAD

**Issue by grannypron** [grannypron/PoR_L10n#15]
[296](https://www.old-games.ru/translate/index.php?translationid=152&page=all#phrase296) Drop ---> Уд.

Not fixed. I meant this string:

![ud](https://user-images.githubusercontent.com/77742895/115530940-e675a680-a29c-11eb-875b-530c310b786f.jpg)

_Originally posted by @Reotor in https://github.com/grannypron/PoR_L10n/issues/12#issuecomment-823919269_

**Comment by grannypron** [comment]
Should be in the latest patch.

**Comment by Reotor** [comment]
Just noticed this issue :( Unfortunately, we cannot use "Уд." here, since the same string is used in the character's item menu and there is a conflict between hotkeys. When the hotkey "У" is pressed, the "exit" (УЙТИ) command is triggered.

![U](https://user-images.githubusercontent.com/77742895/115632731-0777df00-a311-11eb-8558-2d421f989236.jpg)

**Maybe you can replace "УЙТИ" to "НАЗ." here, set hotkey for "УД." to "У" and for "НАЗ." to "Н" ?** I hope this string will not be duplicated in other menus (in this case, a new hotkey conflict may arise in the future)...

**Comment by grannypron** [comment]
Should be good now.

**Comment by grannypron** [comment]
Whoops no I think I did this backwards and made Drop be НАЗ.

**Comment by grannypron** [comment]
Alright I think I have this working,  but I am worried about some side effects.  It feels like the E key is kinda tied to some other things like refreshing the screen.  It seems like we can use the Y key to serve as an Exit hotkey with НАЗ. but it seems a little fishy now like the screen isn't refreshing quite when it should...🤷
