### ISSUE TITLE
Reassign hotkeys for Encampment menu

### ISSUE THREAD

**Issue by grannypron** [grannypron/PoR_L10n#18]
This relates to the encampment menu "Save View Magic Rest Alter Exit" text at D5A9-D5C7 in the UNCOMPRESSED START.EXE which becomes Сох Гер Маг Отд Ф)опц Уйти

Note that I can't use both Отд and опц because they start with the same letter.

**Comment by grannypron** [comment]
Replacement file entries for the offsets in GAME.OVR are below:

// S for Save -> C
**1977A|43
// V for View -> U
**197AB|55
// M for Magic -> V
**197BB|56
// R for Rest -> J
**197CA|4A
// A for Alter -> Not changing now because of duplicate J
//**197D9|4A

**Comment by grannypron** [comment]
![image](https://user-images.githubusercontent.com/19980049/116317599-29da8400-a779-11eb-9ef6-05ced81b3a55.png)

**Comment by grannypron** [comment]
![image](https://user-images.githubusercontent.com/19980049/116317622-34951900-a779-11eb-8863-21e8305379cf.png)

**Comment by grannypron** [comment]
![image](https://user-images.githubusercontent.com/19980049/116317684-48407f80-a779-11eb-800c-049288d565a8.png)

**Comment by Reotor** [comment]
Since the allowable string length has become larger due to the change in hotkeys and we can do different translation for string with dublicate hotkey, the following changes must be made here:

[39](https://www.old-games.ru/translate/index.php?translationid=148&page=all#phrase39) | Save View Magic Rest Alter Exit ---> Сохр Гер Магия Отд **Н**астр Уйти ---> Cj[h Uth Vfubz Jnl **Y**fcnh Eqnb
