### ISSUE TITLE
Track hotkey modifications for all remaining hotkeys

### ISSUE THREAD

**Issue by grannypron** [grannypron/PoR_L10n#23]
This ticket will be for tracking each hotkey left to reassign and creating a GH issue for it.  

I went through the strings and found these:

GAME.OVR:
79|Heal View Take Pool Share Appraise Exit|Р)исц М)гер Е)вз З)пул Ы)дел Ф)оце Уйти
80|Heal View Pool Appraise Exit|Р)исц М)гер З)пул Ф)оц Уйти
98|Money Items Exit|Ь)ден Ш)вещ Уйти
99|View Pool Exit|М)г З)пул Уйти
101| Detect Exit| В)опр. Уйти
102|View Take Pool Share|М)ге Е)вз З)пул Ы)ра
103|View Take Pool|М)г Е)вз З)пул
115|Buy|И)к
118|Buy View Take Pool Share Appraise Exit|И)куп М)гер Е)вз З)пул Ы)раз Ф)оц У)н.
119|Buy View Pool Appraise Exit|И)куп М)гер З)пул Ф)оц Уйти
140|Delay Quit|В)за У)наз
142|Speed Exit|Ы)cкр Уйти
226|Bash|И)би
228| Knock| Л)стк
1003|Display|В)эфф
305|Keep Exit|Л)ос Уйти
384|Sell|Ы)пр
427|Rest   daYs Hours Mins   Inc Dec   Exit|К)от .дНи Р)чс Ь)мн Ш)аг Внз Уйти
455|Sell|Ы)пр
459|Cast|С)зк
460|Memorize|Ь)Запомн
461|Scribe|Ы)Запи
462|Learn|Д)изу
548|Select|Ы)выбор
227|Pick|З)от

START.EXE:
55|Parts color-1 color-2 Size Exit|З)части цвет-1 цвет-2 Ы)рост Уйти
58| Keep Exit| Л)оставить Уйти

As each of these is done, the comment below should be edited to keep track of progress.  Close this tickets when tickets have been created for each of these.  It will be assumed that the replacement strings for the strings above will just be removal of the old hotkey character and ) and then capitalization of the first character after that.  If that is not the case, please add comments below to correct and I will update this description to reflect it.

**Comment by grannypron** [comment]
All tickets have now been filed.

**Comment by Reotor** [comment]
**GAME.OVR:**

79|Heal View Take Pool Share Appraise Exit ---> Исц. Гер. Вз. Пул Дел. Оценить Уйти ---> Bcw. Uth. Dp. Gek Ltk. Jwtybnm Eqnb
80|Heal View Pool Appraise Exit ---> Исц. Гер. Пул Оценить Уйти ---> Bcw. Uth. Gek Jwtybnm Eqnb
98|Money Items Exit ---> Деньг Вещи Уйти ---> Ltymu Dtob Eqnb
99|View Pool Exit ---> Гер. Пул Уйти ---> Uth. Gek Eqnb
101| Detect Exit ---> Опред. Уйти ---> Jghtl. Eqnb
102|View Take Pool Share ---> Гер. Вз. Пул Дел. ---> Uth. Dp. Gek Ltk.
103|View Take Pool ---> Гер. Вз. Пул ---> Uth. Dp. Gek
115|Buy ---> Куп ---> Reg
142|Speed Exit ---> Скор. Уйти ---> Crjh. Eqnb
226|Bash ---> Бить ---> <bnm
228| Knock ---> Стук ---> Cner
1003|Display ---> Анализ ---> Fyfkbp
305|Keep Exit ---> Ост. Уйти ---> Jcn. Eqnb
384|Sell ---> Прод ---> Ghjl
455|Sell ---> Прод ---> Ghjl
459|Cast ---> Закл ---> Pfrk
460|Memorize ---> Запомн. ---> Pfgjvy.
461|Scribe ---> Запис. ---> Pfgbc.
462|Learn ---> Изуч. ---> Bpex.
548|Select ---> Выбор ---> Ds,jh
227|Pick ---> Взл. ---> Dpk.

============================

118|Buy View Take Pool Share Appraise Exit ---> Куп Гер Вз Пул Дел Оценить Уйти ---> Reg Uth Dp Gek Ltk Jwtybnm Eqnb
119|Buy View Pool Appraise Exit ---> Куп Гер Пул Оценить Уйти ---> Reg Uth Gek Jwtybnm Eqnb
427|Rest daYs Hours Mins Inc Dec Exit ---> Сон Дни Часы Мин Шаг Обр Уйти

_*Here we will have to abandon the dots when abbreviating some words, because the first word will not fit with a dot. In order to preserve symmetry and avoid confusion, I propose to do without dots in this string at all (despite the presence of abbreviations)._

============================

**Comment by Reotor** [comment]
80|Heal View Pool Appraise Exit ---> Исц. Гер. Пул Оценить Уйти ---> Bcw. Uth. Gek Jwtybnm Eqnb

**Comment by Reotor** [comment]
98|Money Items Exit ---> Деньг Вещи Уйти ---> Ltymu Dtob Eqnb

**Comment by Reotor** [comment]
99|View Pool Exit ---> Гер. Пул Уйти ---> Uth. Gek Eqnb

**Comment by Reotor** [comment]
101| Detect Exit ---> Опред. Уйти ---> Jghtl. Eqnb

**Comment by Reotor** [comment]
102|View Take Pool Share ---> Гер. Вз. Пул Дел. ---> Uth. Dp. Gek Ltk.

**Comment by Reotor** [comment]
103|View Take Pool ---> Гер. Вз. Пул ---> Uth. Dp. Gek

**Comment by Reotor** [comment]
115|Buy ---> Куп ---> Reg

**Comment by Reotor** [comment]
118|Buy View Take Pool Share Appraise Exit ---> Куп Гер Вз Пул Дел Оценить Уйти ---> Reg Uth Dp Gek Ltk Jwtybnm Eqnb

_*Here we will have to abandon the dots when abbreviating some words, because the first word will not fit with a dot. In order to preserve symmetry, I propose to do without dots in this string at all._

**Comment by Reotor** [comment]
119|Buy View Pool Appraise Exit ---> Куп Гер Пул Оценить Уйти ---> Reg Uth Gek Jwtybnm Eqnb

*Here we will have to abandon the dots when abbreviating some words (See [above](https://github.com/grannypron/PoR_L10n/issues/23#issuecomment-830719837) for details...

**Comment by Reotor** [comment]
140|Delay Quit ???

_Where exactly are these options located? I don't remember..._

**Comment by Reotor** [comment]
142|Speed Exit ---> Скор. Уйти ---> Crjh. Eqnb

**Comment by Reotor** [comment]
**START.EXE:**

55|Parts color-1 color-2 Size Exit ---> Части цвет-**1** цвет-**2** Размер Уйти ---> Xfcnb wdtn-**1** wdtn-**2** Hfpvth Eqnb
58| Keep Exit ---> Оставить Уйти ---> Jcnfdbnm Eqnb

**Comment by grannypron** [comment]
> 140|Delay Quit ???
> 
> _Where exactly are these options located? I don't remember..._

I am thinking that this is in the Done combat submenu.  It lets you postpone the remaining moves in that character's turn until the end of the combat round.

**Comment by Reotor** [comment]
> > 140|Delay Quit ???
> > _Where exactly are these options located? I don't remember..._
> 
> I am thinking that this is in the Done combat submenu. It lets you postpone the remaining moves in that character's turn until the end of the combat round.

140|Delay Quit ---> Позже Уйти ---> Gjp;t Eqnb
