### ISSUE TITLE
The string was reduced from 8 to 4 symbols for some reason...

### ISSUE THREAD

**Issue by Reotor** [grannypron/PoR_L10n#4]
[391](https://www.old-games.ru/translate/index.php?translationid=152&page=all#phrase391) Drop It? ---> Выбросить?

For some reason, when trying to delete a character's item, the "Drop It?" string has been reduced to 4 symbols in RUS patch, although in the original there are 8 symbols:

![DROP_](https://user-images.githubusercontent.com/77742895/114735005-7374a900-9d4d-11eb-8928-55d1f60d636b.jpg)

Also, in many similar places in the game, the words "yes" / "no" are not translated (although they are translated in the translation system). See the picture above.

**Comment by grannypron** [comment]
The Drop/Drop It? problem is fixed in the latest patch.

The Yes/No problem is happening because there is one location where the "Yes No" string is stored in GAME.OVR, but it does not use the ~ for specifying hotkeys.  Until/unless we find a way of changing the hotkeys for that string, changing the "Yes No" to "да нет", will result in the user not being able to select either.  Since the string is in GAME.OVR, there is no uncompressing we can do to make the string longer, either.  Maybe we could change it to  Y)д N)н  ?   Do д  and н serve as recognizable abbreviations for yes / no like y/n does in English?

**Comment by grannypron** [comment]
Opened #5 for the Yes/No problem.

**Comment by Reotor** [comment]
> Do д and н serve as recognizable abbreviations for yes / no like y/n does in English?

Yes

**Comment by grannypron** [comment]
Actually, I think i got the hotkeys switched on this one!  See #5
