### ISSUE TITLE
Hotkeys don't work here

### ISSUE THREAD

**Issue by Reotor** [grannypron/PoR_L10n#9]
At the stage of character creation, when we are asked whether to leave this character, the hotkeys for "yes" ("да")/"no" ("нет") do not work. More precisely, the "Н" ("Y") key works for "YES", but even the Latin "N" does not work for the "NO" option.

![hotkeys](https://user-images.githubusercontent.com/77742895/115094755-585d9100-9f27-11eb-8283-daf05f3fe416.jpg)

Cyrillic symbols ("д" for "да" and "н" for "нет" do not work here at all.

**Comment by grannypron** [comment]
Tracing parallel executions in DOSBox debugger shows that the two keypresses diverge here:
1FC6:1E24  807EEA59            cmp  byte [bp-16],59        ss:[3DB4]=114C   (L keypress)       
vs 
1FC6:1E24  807EEA59            cmp  byte [bp-16],59        ss:[3DB4]=0C59   (Y keypress)

which maps to 1B7A3-1B7A6 in GAME.OVR

Pretty straightforward I think because Y is 59 in hex and L is 4C.

May be able to just change 807EEA59 to 807EEA4C.

**Comment by grannypron** [comment]
Nope, that by itself does not do it.

**Comment by grannypron** [comment]
Yep.  That did it.  Latest patch has the fix
